/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import vista.fMaestros;
import vista.fVentas;

/**
 *
 * @author user
 */
public class fMain extends javax.swing.JFrame {

    /**
     * Creates new form fMain
     */
    public fMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        basicCalendarPaneUI1 = new com.michaelbaranov.microba.calendar.ui.basic.BasicCalendarPaneUI();
        basicDatePickerUI1 = new com.michaelbaranov.microba.calendar.ui.basic.BasicDatePickerUI();
        defaultCalendarResources1 = new com.michaelbaranov.microba.calendar.DefaultCalendarResources();
        microba1 = new com.michaelbaranov.microba.Microba();
        windowsMarkerBarUI1 = new com.michaelbaranov.microba.marker.ui.windows.WindowsMarkerBarUI();
        jToolBar1 = new javax.swing.JToolBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuVentasClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        mnuConfigMaestros = new javax.swing.JMenuItem();

        jMenu6.setText("jMenu6");

        jMenu3.setText("jMenu3");

        jMenu11.setText("jMenu11");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        jMenu1.setText("Ventas");

        mnuVentasClientes.setText("Ventas Clientes");
        mnuVentasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasClientesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVentasClientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compras");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Informes");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Maestros");

        mnuConfigMaestros.setText("Configurar Maestros");
        mnuConfigMaestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConfigMaestrosActionPerformed(evt);
            }
        });
        jMenu5.add(mnuConfigMaestros);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuConfigMaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConfigMaestrosActionPerformed
        fMaestros fmae = new fMaestros();
        fmae.setVisible(true);
        fmae.pack();
        fmae.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_mnuConfigMaestrosActionPerformed

    private void mnuVentasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentasClientesActionPerformed
        fVentas fventa = new fVentas();
        fventa.setVisible(true);
        fventa.pack();
        fventa.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mnuVentasClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.michaelbaranov.microba.calendar.ui.basic.BasicCalendarPaneUI basicCalendarPaneUI1;
    private com.michaelbaranov.microba.calendar.ui.basic.BasicDatePickerUI basicDatePickerUI1;
    private com.michaelbaranov.microba.calendar.DefaultCalendarResources defaultCalendarResources1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToolBar jToolBar1;
    private com.michaelbaranov.microba.Microba microba1;
    private javax.swing.JMenuItem mnuConfigMaestros;
    private javax.swing.JMenuItem mnuVentasClientes;
    private com.michaelbaranov.microba.marker.ui.windows.WindowsMarkerBarUI windowsMarkerBarUI1;
    // End of variables declaration//GEN-END:variables
}
